name: connect-publish
on:
  push:
    branches: [main]

jobs:
  connect-publish:
    name: connect-publish
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: connect.example.com
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/shiny/
